sudo: false
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install:
  - echo "gem 'hammer_cli_foreman', :git => 'https://github.com/theforeman/hammer-cli-foreman.git'" > Gemfile.local
  - echo "gem 'hammer_cli', :git => 'https://github.com/theforeman/hammer-cli.git'" >> Gemfile.local
  - gem update bundler
