FROM registry.access.redhat.com/ubi9/ruby-33
RUN mkdir -p .hammer/cli.modules.d
RUN cat <<EOF > .hammer/cli.modules.d/foreman.yml
:foreman:
  :enable_module: true
  :host: 'http://localhost:3000/'
  :username: 'admin'
  :password: 'changeme'
EOF

RUN cat <<EOF > .hammer/cli.modules.d/katello.yml
:katello:
  :enable_module: true
EOF

RUN cat <<EOF > .hammer/cli_config.yml
:reload_cache: true
:log_dir: '~/.hammer/log'
:log_level: 'debug'
EOF

RUN mkdir hammer-cli-katello
RUN cat <<EOF > .gitconfig
[safe]
	directory = ~/hammer-cli-katello
EOF
WORKDIR hammer-cli-katello
CMD bundle install && bundle exec bash
