---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release gem
    uses: theforeman/actions/.github/workflows/release-gem.yml@v0
    with:
      allowed_owner: Katello
    secrets:
      api_key: ${{ secrets.RUBYGEM_API_KEY }}
